import QtQuick 2.15
import QtQuick.Controls 2.15

// ─────────────────────────────────────────────────────────────────────────────
//  Dashboard.qml
//
//  Requires "dashboard" context property set in main.cpp:
//      DashboardModel dashboard;
//      engine.rootContext()->setContextProperty("dashboard", &dashboard);
//
//  All six values are read directly from the C++ model via property bindings.
//  The onXxxChanged handlers below are auto-generated by Q_PROPERTY NOTIFY —
//  no manual signal declarations needed here.
// ─────────────────────────────────────────────────────────────────────────────
ApplicationWindow {
    id: root
    width:  1160
    height:  540
    visible: true
    title: "BuffDash Quick Demo"

    // ── Bind to C++ model ─────────────────────────────────────────────────────
    //  QML re-evaluates these bindings automatically whenever the C++ setter
    //  emits the corresponding NOTIFY signal.
    readonly property real speed : bridge.speed   // mph
    readonly property real rpm   : bridge.rpm     // rpm
    readonly property real temp1 : bridge.temp1   // °C
    readonly property real temp2 : bridge.temp2   // °C
    readonly property real temp3 : bridge.temp3   // °C
    readonly property real temp4 : bridge.temp4   // °C

    // ── Property-change handlers ──────────────────────────────────────────────
    //  These are NOT signal declarations — they are auto-generated handler slots
    //  for the Q_PROPERTY NOTIFY signals coming from the C++ side.
    onSpeedChanged: {
        console.log("[Dashboard] speed →", speed, "mph")
        progressBar.value = Math.min(speed / 300, 1.0)
    }
    onRpmChanged:   console.log("[Dashboard] rpm →",   rpm,   "rpm")
    onTemp1Changed: console.log("[Dashboard] temp1 →", temp1, "°C")
    onTemp2Changed: console.log("[Dashboard] temp2 →", temp2, "°C")
    onTemp3Changed: console.log("[Dashboard] temp3 →", temp3, "°C")
    onTemp4Changed: console.log("[Dashboard] temp4 →", temp4, "°C")

    // ── Temperature colour palette ────────────────────────────────────────────
    readonly property var tempColors: ["#e8e8e8", "#d4a265", "#e07878", "#d95f5f"]

    // ═════════════════════════════════════════════════════════════════════════
    //  BACKGROUND
    // ═════════════════════════════════════════════════════════════════════════
    Rectangle {
        anchors.fill: parent
        color: "#000000"
    }

    // ═════════════════════════════════════════════════════════════════════════
    //  THROTTLE BAR  (parallelogram via Canvas)
    // ═════════════════════════════════════════════════════════════════════════
    Item {
        id: barContainer
        x:      130
        y:      46
        width:  parent.width - 200
        height: 74

        // Dark track
        Canvas {
            anchors.fill: parent
            onPaint: {
                var ctx  = getContext("2d")
                var skew = 38
                ctx.clearRect(0, 0, width, height)
                ctx.beginPath()
                ctx.moveTo(skew,         0)
                ctx.lineTo(width,        0)
                ctx.lineTo(width - skew, height)
                ctx.lineTo(0,            height)
                ctx.closePath()
                ctx.fillStyle = "#2a2a2a"
                ctx.fill()
            }
        }

        // Gold fill — clipped to current value ratio
        Item {
            id: progressBar

            property real value: 0.0
            Behavior on value { NumberAnimation { duration: 400; easing.type: Easing.OutCubic } }

            anchors {
                left:   parent.left
                top:    parent.top
                bottom: parent.bottom
            }
            width: parent.width * value
            clip:  true

            Canvas {
                // Draw the full bar shape; clip on the parent does the masking
                width:  barContainer.width
                height: parent.height
                onPaint: {
                    var ctx  = getContext("2d")
                    var skew = 38
                    ctx.clearRect(0, 0, width, height)
                    ctx.beginPath()
                    ctx.moveTo(skew,         0)
                    ctx.lineTo(width,        0)
                    ctx.lineTo(width - skew, height)
                    ctx.lineTo(0,            height)
                    ctx.closePath()
                    var grad = ctx.createLinearGradient(0, 0, width, 0)
                    grad.addColorStop(0,   "#c8a84b")
                    grad.addColorStop(0.6, "#b8983a")
                    grad.addColorStop(1,   "#a08228")
                    ctx.fillStyle = grad
                    ctx.fill()
                }
            }
        }
    }

    // ═════════════════════════════════════════════════════════════════════════
    //  SPEED + RPM readouts
    // ═════════════════════════════════════════════════════════════════════════
    Row {
        x:      130
        y:      160
        width:  parent.width - 200
        height: 90

        // Speed
        Item {
            width:  parent.width / 2
            height: parent.height

            Row {
                anchors.verticalCenter: parent.verticalCenter
                anchors.left:          parent.left
                anchors.leftMargin:    10
                spacing: 0

                Text {
                    text:              Math.round(root.speed)
                    font.family:       "Arial Black"
                    font.pixelSize:    82
                    font.bold:         true
                    color:             "#ffffff"
                    verticalAlignment: Text.AlignBottom
                }
                Text {
                    text:           " mph"
                    font.family:    "Arial"
                    font.pixelSize: 24
                    color:          "#aaaaaa"
                    anchors.bottom: parent.bottom
                    bottomPadding:  14
                }
            }
        }

        // RPM
        Item {
            width:  parent.width / 2
            height: parent.height

            Row {
                anchors.verticalCenter: parent.verticalCenter
                anchors.left:          parent.left
                anchors.leftMargin:    30
                spacing: 0

                Text {
                    text:              Math.round(root.rpm)
                    font.family:       "Arial Black"
                    font.pixelSize:    82
                    font.bold:         true
                    color:             "#ffffff"
                    verticalAlignment: Text.AlignBottom
                }
                Text {
                    text:           " rpm"
                    font.family:    "Arial"
                    font.pixelSize: 24
                    color:          "#aaaaaa"
                    anchors.bottom: parent.bottom
                    bottomPadding:  14
                }
            }
        }
    }

    // ═════════════════════════════════════════════════════════════════════════
    //  TEMPERATURE TILES
    // ═════════════════════════════════════════════════════════════════════════
    Row {
        id:      tempRow
        x:       130
        y:       310
        spacing: 18
        width:   parent.width - 200

        Repeater {
            model: 4

            delegate: Rectangle {
                id: tile

                readonly property real tempValue: {
                    if (index === 0) return root.temp1
                    if (index === 1) return root.temp2
                    if (index === 2) return root.temp3
                    return root.temp4
                }

                width:  (tempRow.width - 54) / 4   // 54 = 3 gaps × 18px
                height: 92
                radius: 6
                color:  "#2a2a2a"

                // Subtle border
                Rectangle {
                    anchors.fill: parent
                    radius:       parent.radius
                    color:        "transparent"
                    border.color: "#3a3a3a"
                    border.width: 1
                }

                Column {
                    anchors.centerIn: parent
                    spacing: 4

                    Text {
                        anchors.horizontalCenter: parent.horizontalCenter
                        text:           Math.round(tile.tempValue) + "°C"
                        font.family:    "Arial Black"
                        font.pixelSize: 30
                        font.bold:      true
                        color:          root.tempColors[index]
                        Behavior on color { ColorAnimation { duration: 300 } }
                    }

                    Text {
                        anchors.horizontalCenter: parent.horizontalCenter
                        text:           "Temperature"
                        font.family:    "Arial"
                        font.pixelSize: 13
                        color:          "#888888"
                    }
                }
            }
        }
    }
}